import assert from 'node:assert/strict';
import {createAutosaver} from '../storage/projects.mjs';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const writes=[], statuses=[];
const store={save(document,token){const next=deferred();writes.push({document,token,...next});return next.promise;}};
const saver=createAutosaver(store,(status)=>statuses.push(status));
saver.initialize(null);
const p=saver.enqueue({revision:1});
saver.enqueue({revision:2});saver.enqueue({revision:3});
assert.equal(writes.length,1,'Only one transaction runs at a time');
writes[0].resolve('first');await new Promise(r=>setImmediate(r));
assert.equal(writes.length,2);
assert.deepEqual(writes[1].document,{revision:3},'Pending intermediate saves coalesce into the latest edit');
assert.equal(writes[1].token,'first');
assert.equal(statuses.includes('saved'),false,'An old successful write does not mark newer changes saved');
writes[1].reject(new Error('Quota exceeded'));await p;
assert.equal(statuses.at(-1),'error');assert.equal(saver.unsettled,true);
await saver.enqueue({revision:4});assert.equal(writes.length,2,'Failure pauses automatic writes');
const retry=saver.retry();assert.equal(writes.length,3);assert.equal(writes[2].token,'first');
assert.equal(writes[2].document.revision,4,'Retry writes the latest user edits');
writes[2].resolve('second');await retry;
assert.equal(statuses.at(-1),'saved');assert.equal(saver.unsettled,false);
console.log('Autosave ordering, coalescing, failure visibility, latest-edit retry, and token retention passed');
